"""empty message

Revision ID: fa338adce0b0
Revises: a1837d07a79a
Create Date: 2021-12-13 04:08:43.226447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa338adce0b0'
down_revision = 'a1837d07a79a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_address',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ip_address', sa.String(length=128), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('expired_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_address')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('access_address')
    # ### end Alembic commands ###
